//
// Created by strohhalm on 28.06.15.
//

#ifndef NWEBMEDIA_NSERVICECLIENTSECURITY_H
#define NWEBMEDIA_NSERVICECLIENTSECURITY_H

#define NCOMPONENT_SERVICE_CLIENT_SECURIY "security"

#endif //NWEBMEDIA_NSERVICECLIENTSECURITY_H
