//
// Created by strohhalm on 14.07.15.
//

#ifndef NWEBMEDIA_NSERVICECLIENTINFRA_H
#define NWEBMEDIA_NSERVICECLIENTINFRA_H

#define NCOMPONENT_SERVICE_CLIENT_INFRA "infrastructure"

#endif //NWEBMEDIA_NSERVICECLIENTINFRA_H
