CREATE TABLE `nox`.`NOX_SEC_USR_GRP` (
  `USER_ID` INT NOT NULL,
  `GROUP_ID` INT NOT NULL,
  `VALID_FROM` DATE NOT NULL,
  `VALID_TO` DATE NULL,
  `ACTIVE` INT NOT NULL,
  PRIMARY KEY (`USER_ID`, `GROUP_ID`),
  INDEX `FK_NOX_SEC_GROUP_idx` (`GROUP_ID` ASC),
  CONSTRAINT `FK_NOX_SEC_USER`
    FOREIGN KEY (`USER_ID`)
    REFERENCES `nox`.`NOX_SEC_USER` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_NOX_SEC_GROUP`
    FOREIGN KEY (`GROUP_ID`)
    REFERENCES `nox`.`NOX_SEC_GROUP` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
