CREATE TABLE `NOX_SEC_USER` (
  `ID` int(11) NOT NULL,
  `VALID_FROM` date NOT NULL,
  `VALID_TO` date DEFAULT NULL,
  `USER_NAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(50) NOT NULL,
  `FIRST_NAME` varchar(50) NOT NULL,
  `LAST_NAME` varchar(50) NOT NULL,
  `EMAIL` varchar(50) NOT NULL,
  `ACTIVE` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `USER_NAME_UNIQUE` (`USER_NAME`),
  INDEX `IND_USR_NAME` (`USER_NAME`,`VALID_FROM`,`VALID_TO`));