CREATE TABLE nox.NOX_SEC_GROUP (
  ID INT NOT NULL,
  VALID_FROM DATE NOT NULL,
  VALID_TO DATE NULL,
  GROUP_NAME VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(256) NULL,
  ACTIVE INT NOT NULL,
  PRIMARY KEY (ID),
  UNIQUE INDEX GROUP_NAME_UNIQUE (GROUP_NAME ASC),
  INDEX IND_GRP_NAME (GROUP_NAME ASC, VALID_FROM ASC, VALID_TO ASC));
